### ISSUE TITLE
feat: implement SSH key deletion when disabling the "passphrase" option

### ISSUE THREAD

**Issue by stevenlei** [teaxyz/teaBASE#12]
When disabling the "Passphrase" option
<img width="451" alt="SSH Key Toggle Switch" src="https://github.com/user-attachments/assets/e71def02-222c-416e-b1c4-cb83171ea096" />

I propose the following workflow:

Currently, enabling this feature generates two files:
- `~/.ssh/id_ed25519.pub` (public key)
- `~/.ssh/id_ed25519` (private key)

### Proposed Behavior When Switching Off

When toggling off, we should show a confirmation alert:

**Alert Message:**  
"This will delete the SSH keys at `~/.ssh/id_ed25519`. Please ensure you have a backup if needed."

**Options:**
1. "Delete Keys" - Proceeds with deletion
2. "Print Recovery Kit" - Opens print dialog (requires original passphrase verification)
3. "Cancel" - Keeps keys and reverts toggle

### Additional Consideration

We could verify if the keys were generated by teaBASE by checking for the "Generated by teaBASE" comment in the public key. However, is this verification necessary, or should we simply trust the user's intent when they use the toggle?

Thoughts on this approach?

**Comment by mxcl** [comment]
Disabling the passphrase should decrypt the private key and rewrite it without the passphrase encryption IMO. I am not sure how to do that.

Disabling ssh (the toggle above) deletes the keys already.

**Comment by jhheider** [comment]
`ssh-keygen -p [-P old_passphrase] [-N new_passphrase] [-f keyfile]`

**Comment by stevenlei** [comment]
@mxcl Ah, I see, I have oversee it. Thanks for clarifying.

@jhheider Thanks for sharing this

**Comment by stevenlei** [comment]
@mxcl Ah, I see, I have overlooked it. Thanks for clarifying.

@jhheider Thanks for sharing this
