### ISSUE TITLE
Menu Disappears When Creating Backup Without SSH Passphrase

### ISSUE THREAD

**Issue by 0xsingular** [teaxyz/teaBASE#18]
When I click "Print Recovery Kit" without setting an SSH passphrase, the teaBASE menu disappears completely. 

Steps to Reproduce:

Open teaBASE.
Don’t set an SSH passphrase.
Click "Print Recovery Kit".

Environment:

Version: teaBASE 0.5.0
OS: macOS Ventura 13.6.4

**Comment by stevenlei** [comment]
It's working on my end with these settings:
<img width="464" alt="image" src="https://github.com/user-attachments/assets/cb0db418-72e4-44a8-895b-795169a40be0" />

I tried to reproduce with the following steps:
1. Create a new key by enabling **Secure Shell (SSH)**
2. Do not turn on **Passphrase**
3. Click **Print Recovery Kit...**
4. A print dialog will be displayed

Could you please try to restart the System Preference, and try it again?

**Comment by 0xsingular** [comment]
I really don’t want to uninstall everything, but even now, when I click 'Print Recovery Kit' > 'Deny,' I get a similar result.

Feels like it might be something specific to this macOS version or device

https://github.com/user-attachments/assets/846d3e54-e1b8-43b5-9a92-1269780f4d50

**Comment by stevenlei** [comment]
Ah, I see. This asks for permission to get your GPG key from the keychain. Yes we should have a proper error handling regarding this.
