### ISSUE TITLE
Generate Pack -> “make-clean-install-pack.command” cannot be opened

### ISSUE THREAD

**Issue by stevenlei** [teaxyz/teaBASE#43]
“make-clean-install-pack.command” cannot be opened because it is from an unidentified developer.

<img width="480" alt="image" src="https://github.com/user-attachments/assets/52daf38d-d2cd-4a74-bfad-d518bb55be9e" />

Maybe we need to sign this script too

**Comment by mxcl** [comment]
Everything is deep signed. Maybe `.command` files are not included.

**Comment by mxcl** [comment]
k it's the quarantine bit not getting unset for some reason, though that makes no difference to anything since we can’t fix that. It's Apple’s bug. Will rename them to `.sh` and open them the original way, sigh.
